"""init tables

Revision ID: 025f2fc28fb0
Revises: 
Create Date: 2025-09-08 20:03:58.924763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '025f2fc28fb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batt_description', schema=None) as batch_op:
        batch_op.drop_column('batt_temp')

    with op.batch_alter_table('batt_fault_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolve', sa.String(length=50), nullable=True))
        batch_op.drop_column('resolve_text')

    with op.batch_alter_table('batt_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batt_remaining_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('batt_remaining_time')

    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('security_qn',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('tbl_user_email_key'), type_='unique')
        batch_op.drop_column('ip')
        batch_op.drop_column('ph_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('tbl_user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('security_qn',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('phone')

    with op.batch_alter_table('batt_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batt_remaining_time', postgresql.INTERVAL(), autoincrement=False, nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('batt_remaining_time_min')

    with op.batch_alter_table('batt_fault_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolve_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('resolve')

    with op.batch_alter_table('batt_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batt_temp', sa.NUMERIC(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
